apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-webserver
  namespace: default
  labels:
    app: apache-webserver
spec:
  replicas: 20
  selector:
    matchLabels:
      app: apache-webserver
  template:
    metadata:
      labels:
        app: apache-webserver
    spec:
      containers:
      - name: apache
        image: j123qwe/apache-k8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      nodeSelector:
        nodeType: utility
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-webserver-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: ha.gogo.yoducks.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: apache-webserver
                port:
                  number: 80
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: apache-webserver
  namespace: default
spec:
  selector:
    app: apache-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
